server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.159.134:7001
        - 192.168.159.134:7002
        - 192.168.159.134:7003
        - 192.168.159.134:7004
        - 192.168.159.134:7005
        - 192.168.159.134:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  rabbitmq:
    host: 192.168.159.129
    username: admin
    password: 1111
    virtual-host: /


#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY